services:
  # Servicio MongoDB
  mongo:
    image: mongo:6.0
    container_name: visilab_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: visilab_annotator
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/logs:/var/log/mongodb
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - visilab_network

  # Servicio Backend
  backend:
    build: ./backend
    container_name: visilab_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - ./backend:/app
      - ./backend/datasets:/app/datasets
      - ./backend/ai_models:/app/ai_models
    command: flask run --host=0.0.0.0 --port=5000 --reload 
    depends_on:
      - mongo
    networks:
      - visilab_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Servicio Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: visilab_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend
    networks:
      - visilab_network

# Red para comunicaci√≥n entre servicios
networks:
  visilab_network:
    driver: bridge
